### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by marczellm** [andreasjansson/ly2midi#1]
I'm using this code in my project (https://github.com/marczellm/algorimp) and I realized that you didn't specify a license.

I would like to know if you are OK with me reusing and modifying it, and under what conditions. Maybe you could add a license.

**Comment by andreasjansson** [comment]
Hi @marczellm, glad to hear ly2midi still works five years later :) I added a GNU GPL v3 LICENSE file. Hope that works for you!

**Comment by marczellm** [comment]
Thanks!
